In [ ]:
# importing required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Preprocess the Dataset

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/project/House Price India.csv')
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000

In [ ]:
df.shape

(14620, 23)

In [ ]:
df.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14620 entries, 0 to 14619
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     14620 non-null  int64
 1   Date                                   14620 non-null  int64
 2   number of bedrooms                     14620 non-null  int64
 3   number of bathrooms                    14620 non-null  float64
 4   living area                            14620 non-null  int64
 5   lot area                               14620 non-null  int64
 6   number of floors                       14620 non-null  float64
 7   waterfront present                     14620 non-null  int64
 8   number of views                        14620 non-null  int64
 9   condition of the house                 14620 non-null  int64
 10  grade of the house                     14620 non-null  int64
 11  Area of the house(excluding basement)  14620 non-null  int64
 12  Area of the basement                   14620 non-null  int64
 13  Built Year                             14620 non-null  int64
 14  Renovation Year                        14620 non-null  int64
 15  Postal Code                            14620 non-null  int64
 16  Lattitude                              14620 non-null  float64
 17  Longitude                              14620 non-null  float64
 18  living_area_renov                      14620 non-null  int64
 19  lot_area_renov                         14620 non-null  int64
 20  Number of schools nearby               14620 non-null  int64
 21  Distance from the airport              14620 non-null  int64
 22  Price                                  14620 non-null  int64
dtypes: float64(4), int64(19)
memory usage: 2.6 MB

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Initializing encoder

le = LabelEncoder()

convert the string type to int type

In [ ]:
df['number of bedrooms'] = le.fit_transform(df['number of bedrooms'])

In [ ]:
df.drop(['number of bedrooms','Date'],axis =1,inplace =True)

In [ ]:
df.head()

,id,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,Area of the house(excluding basement),...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,2.50,3650,9050,2.0,0,4,5,10,3370,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,2.50,2920,4000,1.5,0,0,5,8,1910,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,2.75,2910,9480,1.5,0,0,3,8,2910,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,2.50,3310,42998,2.0,0,0,3,9,3310,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,2.00,2710,4500,1.5,0,0,4,8,1880,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000

In [ ]:
df.Price.value_counts()

450000    114
350000    113
400000    104
375000    103
550000    102
         ...
561600      1
856500      1
907687      1
307999      1
146000      1
Name: Price, Length: 2901, dtype: int64

In [ ]:
x= df.drop(['Price'],axis =1)
y = df.Price

In [ ]:
y = le.fit_transform(y)

In [ ]:
y

array([2849, 2768, 2748, ...,  241,  222,   60])

split the data (Training & Testing)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [ ]:
xtrain.shape

(11696, 20)

In [ ]:
xtest.shape

(2924, 20)

Build the ANN Model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units=128,activation = 'relu'))

# Adding the second hidden layer
classifier.add(Dense(units=64,activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units=1, activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
# compiling the ANN model
 
classifier.compile(optimizer = 'adam',loss= 'mse',metrics = ['mse'])

Training the model

In [ ]:
classifier.fit(xtrain,ytrain,batch_size = 10,epochs = 100)

Epoch 1/100
1170/1170 [==============================] - 4s 3ms/step - loss: 2584614.5000 - mse: 2584614.5000
Epoch 2/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584617.2500 - mse: 2584617.2500
Epoch 3/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.0000 - mse: 2584615.0000
Epoch 4/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584617.7500 - mse: 2584617.7500
Epoch 5/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.2500 - mse: 2584616.2500
Epoch 6/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584617.0000 - mse: 2584617.0000
Epoch 7/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584613.2500 - mse: 2584613.2500
Epoch 8/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584614.5000 - mse: 2584614.5000
Epoch 9/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584617.7500 - mse: 2584617.7500
Epoch 10/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584613.7500 - mse: 2584613.7500
Epoch 11/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.0000 - mse: 2584615.0000
Epoch 12/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.0000 - mse: 2584616.0000
Epoch 13/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584617.2500 - mse: 2584617.2500
Epoch 14/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584616.5000 - mse: 2584616.5000
Epoch 15/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584617.0000 - mse: 2584617.0000
Epoch 16/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 17/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 18/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.7500 - mse: 2584615.2500
Epoch 19/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584615.5000 - mse: 2584615.5000
Epoch 20/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 21/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 22/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.0000 - mse: 2584615.0000
Epoch 23/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.0000 - mse: 2584614.0000
Epoch 24/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 25/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584617.0000 - mse: 2584617.0000
Epoch 26/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584615.2500 - mse: 2584615.2500
Epoch 27/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 28/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.5000 - mse: 2584616.5000
Epoch 29/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.0000 - mse: 2584615.5000
Epoch 30/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.7500 - mse: 2584616.7500
Epoch 31/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584614.5000 - mse: 2584614.5000
Epoch 32/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584615.0000 - mse: 2584615.0000
Epoch 33/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 34/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.0000 - mse: 2584616.0000
Epoch 35/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.2500 - mse: 2584616.0000
Epoch 36/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 37/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584615.0000 - mse: 2584615.0000
Epoch 38/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584616.7500 - mse: 2584616.7500
Epoch 39/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584612.7500 - mse: 2584612.7500
Epoch 40/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 41/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.0000 - mse: 2584615.0000
Epoch 42/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584617.5000 - mse: 2584617.5000
Epoch 43/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 44/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584614.2500 - mse: 2584614.0000
Epoch 45/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.0000 - mse: 2584616.0000
Epoch 46/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 47/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.5000 - mse: 2584615.5000
Epoch 48/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.7500 - mse: 2584616.7500
Epoch 49/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 50/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584618.2500 - mse: 2584618.2500
Epoch 51/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584613.0000 - mse: 2584613.0000
Epoch 52/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.0000 - mse: 2584614.0000
Epoch 53/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.2500 - mse: 2584615.2500
Epoch 54/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.5000 - mse: 2584615.5000
Epoch 55/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 56/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584616.0000 - mse: 2584616.0000
Epoch 57/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.0000 - mse: 2584615.0000
Epoch 58/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.2500 - mse: 2584615.2500
Epoch 59/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.0000 - mse: 2584614.0000
Epoch 60/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.5000 - mse: 2584615.2500
Epoch 61/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.5000 - mse: 2584614.5000
Epoch 62/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 63/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584615.0000 - mse: 2584615.0000
Epoch 64/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.0000 - mse: 2584616.0000
Epoch 65/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.5000 - mse: 2584616.5000
Epoch 66/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.2500 - mse: 2584616.2500
Epoch 67/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 68/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584615.5000 - mse: 2584615.5000
Epoch 69/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.2500 - mse: 2584615.2500
Epoch 70/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.5000 - mse: 2584615.5000
Epoch 71/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.7500 - mse: 2584615.7500
Epoch 72/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.2500 - mse: 2584615.2500
Epoch 73/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584616.2500 - mse: 2584616.5000
Epoch 74/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584615.5000 - mse: 2584615.5000
Epoch 75/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.7500 - mse: 2584614.7500
Epoch 76/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.7500 - mse: 2584616.7500
Epoch 77/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584611.5000 - mse: 2584611.5000
Epoch 78/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.5000 - mse: 2584615.5000
Epoch 79/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 80/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584615.7500 - mse: 2584615.7500
Epoch 81/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.0000 - mse: 2584616.0000
Epoch 82/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584617.5000 - mse: 2584617.5000
Epoch 83/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584613.2500 - mse: 2584613.2500
Epoch 84/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.0000 - mse: 2584614.0000
Epoch 85/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584613.7500 - mse: 2584613.7500
Epoch 86/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584615.5000 - mse: 2584615.5000
Epoch 87/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.7500 - mse: 2584616.7500
Epoch 88/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.0000 - mse: 2584616.0000
Epoch 89/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 90/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.5000 - mse: 2584616.5000
Epoch 91/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584614.5000 - mse: 2584614.5000
Epoch 92/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584613.2500 - mse: 2584613.2500
Epoch 93/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584617.2500 - mse: 2584617.2500
Epoch 94/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.2500 - mse: 2584615.2500
Epoch 95/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584616.0000 - mse: 2584616.0000
Epoch 96/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584615.2500 - mse: 2584615.5000
Epoch 97/100
1170/1170 [==============================] - 3s 2ms/step - loss: 2584615.5000 - mse: 2584615.2500
Epoch 98/100
1170/1170 [==============================] - 3s 3ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 99/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584614.2500 - mse: 2584614.2500
Epoch 100/100
1170/1170 [==============================] - 2s 2ms/step - loss: 2584617.5000 - mse: 2584617.5000

Testing the model

In [ ]:
y_pred = classifier.predict(xtest)

92/92 [==============================] - 0s 1ms/step

In [ ]:
pd.DataFrame({'Actual value':ytest.flatten(),'predicted value':y_pred.flatten().astype('int')}).head(20)

    Actual value  predicted value
0            487                0
1           2744                0
2           1176                0
3           1700                0
4           2058                0
5            492                0
6           2680                0
7            446                0
8           2777                0
9            853                0
10           345                0
11           291                0
12          1082                0
13           621                0
14          1422                0
15           960                0
16          1778                0
17           520                0
18           668                0
19          2451                0

In [ ]:
print(len(ytest))
print(len(y_pred))

2924
2924